name: Build PR

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'
      - 'src/main/resources/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        id: build
        with:
          arguments: -Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.fromEnv=JAVA_HOME build
